<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationTitle>Cascade Windows</ApplicationTitle>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <Company>CascadeWindows</Company>
    <Product>Cascade Windows</Product>
    <Copyright>Copyright © 2025 - Licensed under GPL v3</Copyright>
    <Description>Cascade all open windows on the desktop</Description>
  </PropertyGroup>

</Project>